version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout

  deploy-dev:
    machine:
      enabled: true
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Set CI=false
          command: echo "export CI=false" >> $BASH_ENV
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build application
          command: npm run build:dev
      - store_artifacts:
          path: build
      - run:
          name: Install rsync
          command: |
            sudo apt-get update && sudo apt-get install -y rsync
      - run:
          name: Deploy to dev-server
          command: |
            rsync -azP -e "ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_rsa" /home/circleci/project/build/* $AWS_USER_NAME@$AWS_HOST:/var/www/cbms_frontend/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only:
                - main
