#v1
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node CI/CD 

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install NPM Dependencies
        run: npm i
      - name: Build Project
        run: npm run build
      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist
  # Deploy Job
  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     # - name: Download artifact
  #     #   uses: actions/download-artifact@v2
  #     #   with:
  #     #     name: production-files
  #     #     path: ./dist
  #     - uses: actions/checkout@v2
  #     - name: rsync deployments
  #       uses: burnett01/rsync-deployments@5.1
  #       with:
  #         switches: -avzr --delete
  #         path: ./dist/
  #         remote_path: /mnt/data/home/master/applications/nnymekrpaf/tmp/
  #         remote_host: ${{ secrets.HOST }}
  #         remote_user: ${{ secrets.USERNAME }}
  #         remote_key: "${{ secrets.KEY }}"
